libs = stm32f1xx_hal_gpio_ex.o stm32f1xx_hal_tim.o stm32f1xx_hal_tim_ex.o stm32f1xx_hal_uart.o
libs += stm32f1xx_hal.o stm32f1xx_hal_rcc.o stm32f1xx_hal_rcc_ex.o stm32f1xx_hal_gpio.o
libs += stm32f1xx_hal_dma.o stm32f1xx_hal_cortex.o stm32f1xx_hal_pwr.o stm32f1xx_hal_flash.o
libs += stm32f1xx_hal_flash_ex.o stm32f1xx_hal_exti.o

lib-y += $(addprefix lib/,$(libs))